service: lambda-rust-sqlite3-efs

provider:
  architecture: arm64
  name: aws
  memorySize: 128
  runtime: provided.al2
  region: us-east-1
  timeout: 7
  logRetentionInDays: 3
  iam:
    role:
      statements:
        # Allow functions to mount, write and gives root access
        - Effect: Allow
          Action: 
            - 'elasticfilesystem:ClientMount'
            - 'elasticfilesystem:ClientWrite'
          Resource: ${ssm:/lambda-rust-sqlite3-efs/default/EFS_ARN}
  vpc:
    securityGroupIds: ${ssm:/lambda-rust-sqlite3-efs/default/VPC_SG_IDS}
    subnetIds: ${ssm:/lambda-rust-sqlite3-efs/default/VPC_SUBNET_IDS}
  environment:
    RUST_LOG: info
    DATABASE_PATH: /mnt/volume/users.db

package:
  patterns:
    - '!./**'
    - ./bootstrap

functions:
  api:
    handler: bootstrap
    fileSystemConfig:
      localMountPath: /mnt/volume
      arn: ${ssm:/lambda-rust-sqlite3-efs/default/EFS_AP_ARN}
    layers:
      - arn:aws:lambda:us-east-1:753240598075:layer:LambdaAdapterLayerArm64:16
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
        
